sudo: required
services:
  - docker

before_install:
  - docker build -t daniloercolano/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run daniloercolano/react-test npm test -- --coverage

after_success:
  - docker build -t daniloercolano/multi-client ./client
  - docker build -t daniloercolano/multi-nginx ./nginx
  - docker build -t daniloercolano/multi-server ./server
  - docker build -t daniloercolano/multi-worker ./worker


